### ISSUE TITLE
Exceptions on the app#edit

### ISSUE THREAD

**Issue by cycomachead** [saasbook/esaas-engagements#13]
Not sure where this is coming from, but I can't seem to edit apps:
https://esaas-engagements.herokuapp.com/apps/143/edit

**Comment by armandofox** [comment]
sorry, i had forgotten to run a migration when i pushed the updated app.

what's your heroku email address, i'll make you and the GSI's co-owners of all the cs169-related apps:

- esaas-engagements.herokuapp.com
- cs-coursequestionbank.herokuapp.com - aliased as questionbank.saasbook.info

there's a few 'toy' apps that go with the assignments, i'll get to those later.  2 paper deadlines today.

Armando Fox (pronouns: he, him)
Professor, Computer Science Division
Faculty Advisor, Digital Learning Strategy & MOOCLab
UC Berkeley Campus Equity Advisor
581 Soda Hall MC#1776, Berkeley, CA 94720-1776
+1.510.642.6820 / http://www.cs.berkeley.edu/~fox <http://www.cs.berkeley.edu/~fox>

Learn to build software free at saas-class.org
